import * as fs from 'node:fs';
import * as path from 'node:path';

// Every generated file is read by an agent that may know nothing about Kanbrain, so each one opens
// by saying where it came from and where to look for the rest (USAGE.md and the two config files).
export const GENERATED_FILE_HEADER = `> This file was generated by the Kanbrain VS Code extension, which connects this workspace to its Azure DevOps board and already gathers the relevant information for you. For how Kanbrain works, read \`.kanbrain/USAGE.md\`. Its configuration lives in \`.kanbrain/config.json\` (shared and committed: organization/project, skills, workflow steps with their Definition of Done, profiles, colors) and \`.kanbrain/config.local.json\` (this machine only: local repository paths, selected profile, AI provider command, display preferences).

---

`;

export function writeGeneratedFile(workspaceRoot: string, fileName: string, content: string): string {
  const generatedDir = path.join(workspaceRoot, '.kanbrain', 'generated');
  fs.mkdirSync(generatedDir, { recursive: true });
  fs.writeFileSync(path.join(generatedDir, fileName), `${GENERATED_FILE_HEADER}${content}`, 'utf-8');
  return path.join('.kanbrain', 'generated', fileName);
}
